name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: # Manually trigger workflow


jobs:

  buildAndTest:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to server and execute commands
        run: |
          mkdir -p ~/.ssh/
          echo -n "${{ secrets.PEM_KEY }}" > ~/.ssh/id_rsa.pem
          chmod 600 ~/.ssh/id_rsa.pem
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

          # Connect to server and execute commands
          ssh -i ~/.ssh/id_rsa.pem ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
            sudo yum update
            sudo su
            docker stop \$(docker ps -q)
            docker rm -f \$(docker ps -aq)
            docker rmi -f \$(docker images -q)
            docker pull boro2001/intellispeak:latest
            docker run -d -p 80:80 --name intellispeak-service --restart always boro2001/intellispeak:latest
          EOF
