name: deploy

on:
  push:
    branches:
      - master


jobs:

  buildAndTest:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to server and execute commands
        run: |
          mkdir -p ~/.ssh/
          echo -n "${{ secrets.PEM_KEY }}" > ~/.ssh/id_rsa.pem
          chmod 600 ~/.ssh/id_rsa.pem
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

          # Connect to server and execute commands
          ssh -i ~/.ssh/id_rsa.pem ${{ secrets.USERNAME }}@${{ secrets.HOST }} "whoami"
