name: buildAndTest

on:
  push:
    branches:
      - master


jobs:

  buildAndTest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build and test Frontend
        run: |
          cd frontend/
          npm install
          docker build .

      - name: Docker Build and Push
        if: success()
        env:
          DOCKER_HUB_USERNAME: ${{ $DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN:  ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          docker build -t $DOCKER_HUB_USERNAME/intellispeak:latest frontend/
          echo $DOCKER_HUB_TOKEN | docker login docker.io -u $DOCKER_HUB_USERNAME --password-stdin
          docker push $DOCKER_HUB_USERNAME/intellispeak:latest